name: Deploy to Beget (minimal FTP)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      - name: Upload via FTPS (no build)
        env:
          FTP_HOST: vladizm5.beget.tech 
          FTP_USER: vladizm5_testuser
          FTP_PASS: Wkf!B2sHROcj
        run: |
          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e "
            set ftp:passive-mode true;
            set ftp:ssl-allow true;
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set cmd:fail-exit true;

            # Зеркалим локальные файлы на сервер
            mirror -R \
              --parallel=2 \
              --exclude-glob .git* \
              --exclude-glob .github/** \
              --exclude-glob node_modules/** \
              . /;
            bye
          "
