name: Deploy to Beget (FTPS, no external actions)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}     # запуск кнопкой

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Забираем код
      - uses: actions/checkout@v4

      # 2) (Опционально) сборка фронтенда. Если статика без сборки — удалите шаги 2–4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build

      # 3) Ставим lftp (клиент с зеркалированием)
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      # 4) Деплой содержимого dist/ в public_html/ по FTPS
      - name: Deploy via lftp (FTPS)
        env:
          FTP_HOST: vladizm5.beget.tech
          FTP_USER: vladizm5_testuser
          FTP_PASS: Wkf!B2sHROcj
          LOCAL_DIR: dist/                 # если у вас build/, поменяйте
          REMOTE_DIR: public_html/         # целевой каталог на Beget
        run: |
          test -d "$LOCAL_DIR" || (echo "No $LOCAL_DIR folder. Build step missing?" && exit 1)

          lftp -u "$FTP_USER","$FTP_PASS" "$FTP_HOST" -e "
            set ftp:ssl-force true;            # принудительно TLS
            set ftp:ssl-protect-data true;     # шифровать данные
            set net:max-retries 2;
            set cmd:fail-exit true;

            # Создать целевую папку, если нет
            mkdir -p $REMOTE_DIR;

            # Зеркалим локальную папку на сервер (обновляет/добавляет/удаляет)
            mirror -R \
              --delete \
              --parallel=4 \
              --exclude-glob .git* \
              --exclude-glob .github/** \
              --exclude-glob node_modules/** \
              \"$LOCAL_DIR\" \"$REMOTE_DIR\";
            bye
          "
